apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: lesson16
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "default"
  resources:
    requests:
      storage: 1Gi